
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<본인의디비이름>
    username: <본인의 db의 유저이름>
    password: <아이디>
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true